### ISSUE TITLE
TypeError: Invalid non-string/buffer chunk

### ISSUE THREAD

**Issue by greypants** [nfroidure/ttf2woff2#12]
I have a feeling this may be an NPM issue... but this error randomly started popping up today:

```bash
/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
aughtException",(function(ex){if(!(ex instanceof ExitStatus)){throw ex}}));Mod
                                                                    ^
TypeError: Invalid non-string/buffer chunk
    at chunkInvalid (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:421:10)
    at readableAddChunk (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:176:12)
    at DuplexWrapper.Readable.push (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
    at DuplexWrapper._forwardRead (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:95:10)
    at DuplexWrapper._read (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/duplexer2/index.js:83:8)
    at DuplexWrapper.Readable.read (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:377:10)
    at resume_ (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/lib/_stream_readable.js:758:12)
    at afterTick (/home/travis/build/vigetlabs/gulp-starter/node_modules/gulp-imagemin/node_modules/imagemin/node_modules/stream-combiner2/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
    at process._tickCallback (node.js:355:11)
```

Once passing builds on Travis CI will fail with this error if I re-run them today. 
https://travis-ci.org/vigetlabs/vigetlabs/gulp-starter/builds/80556359

Not sure what's going on, but thought I'd document this here. This seems to be happening with a few other packages as well, link `gifcicle` and other things bundled with `imagemin`.

**Comment by nfroidure** [comment]
@greypants  Just updated a new version, could you test and tel if the issue is still there?

**Comment by greypants** [comment]
Thanks! The issue actually mysteriously went a way the next day... with no changes. Seems to have been a temporary glitch with NPM that was resolved (after I spent a few hours hitting my head against a wall :D).
