### ISSUE TITLE
Error: EPERM: operation not permitted, open

### ISSUE THREAD

**Issue by Kiee** [nfroidure/ttf2woff2#24]
```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EPERM: operation not permitted, open 'd:\CODE\project\node_modules\ttf2woff2\jssrc\ttf2woff2.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.Module._extensions..js (module.js:421:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (d:\CODE\project\node_modules\ttf2woff2\jssrc\index.js:3:27)
    at Module._compile (module.js:413:34)
```

I've set the permissions of project folder to read/write for all users recursively via folder security in windows and i've tried running the gulp task as admin.

When I try to open ttf2woff2\jssrc\ttf2woff2.js in notepad as administrator I get: You don't have permission to open this file, contact the file owner or an administrator to obtain permission.

I'm the only user with access and im the owner of the file. Still cannot use.

OS Windows 10, node version 5.9.1

**Comment by nfroidure** [comment]
I think your antivirus software may be the source of your problem see https://github.com/nfroidure/ttf2woff2/issues/7.

Anyway this looks like a windows specific issue and i'm not maintaining this library for this os. I'll merge any PR that improve windows support though.
