### ISSUE TITLE
/Error -  "Path must be a string. Received undefined" on node 6.0.0

### ISSUE THREAD

**Issue by gkorland** [nfroidure/ttf2woff2#26]
```
project/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["re
```

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:191:56
    at Array.forEach (native)
    at trackContentSources (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:188:20)
    at InputSourceMapStore.trackLoaded (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:255:3)
    at fromString (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:32:8)
    at InputSourceMapStore.track (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/utils/input-source-map-tracker.js:236:5)
    at Object.whenDone (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/clean.js:145:44)
    at processNext (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:105:13)
    at importFrom (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at processNext (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:104:16)
    at importFrom (/home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:79:10)
    at /home/guy/WebstormProjects/selfpointrest/node_modules/clean-css/lib/imports/inliner.js:325:9
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by nfroidure** [comment]
I didn't try NodeJS 6 atm but in the meantime, can you provide more informations like your OS, you NPM version etc... Also, feel free to PR the project with a fix.

**Comment by nfroidure** [comment]
gulp-iconfont seems to work on Node 6 https://travis-ci.org/nfroidure/gulp-iconfont/jobs/129117863

**Comment by puzrin** [comment]
@nfroidure i confirm that javascript version is broken. That happened on fontello, it runs on old ubuntu 12.04 LTS without native C++11 compiler. On install it tries fallback to jssrc and generated font are bad.

If i force C++11 use via env before `npm install`, then everything is ok.

**Comment by nfroidure** [comment]
Hi guys,

I no longer use icon fonts so i will probably spend less time on the issues of the gulp-iconfont tool chain.

Feel free to PR though, i'll be happy to merge any useful change for those who till use it and add its author as a collaborator in order for him to work without having to rely on me.

**Comment by puzrin** [comment]
If anyone still interested - here is experimental webassembly build https://github.com/fontello/wawoff2. Works in node 8+. No need to rebuild anymore after install & node version change.

**Comment by nfroidure** [comment]
Node6 no supported anymore
