### ISSUE TITLE
Red Hat 6.6 | npm install error 

### ISSUE THREAD

**Issue by mayko780** [nfroidure/ttf2woff2#27]
Hey,

I'm trying to install tt2woff2 on Red Hat 6.6, but I'm getting following error:
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOTFOUND nodejs.org
gyp ERR! stack     at errnoException (dns.js:44:10)
gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
gyp ERR! System Linux 2.6.32-504.8.1.el6.x86_64
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /XXXX/node_modules/ttf2woff2
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
```
Any suggestions?

**Comment by nfroidure** [comment]
Looks like it is unrelated with ttf2woff2, check your internet connection.
