### ISSUE TITLE
Parsing of the input font failed

### ISSUE THREAD

**Issue by KW1231** [nfroidure/ttf2woff2#35]
OS:     Win 10
node: v7.10.0
npm: v4.2.0

I got this error when trying this: >cat arial.ttf | ttf2woff2 >> A.woff2
```
Parsing of the input font failed
    at BufferStream._bufferStreamCallbackWrapper (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ttf2woff2\node_mod
ules\bufferstreams\src\index.js:48:11)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at BufferStream.emit (events.js:188:7)
    at finishMaybe (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ttf2woff2\node_modules\readable-stream\lib\_stre
am_writable.js:607:14)
    at endWritable (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ttf2woff2\node_modules\readable-stream\lib\_stre
am_writable.js:615:3)
    at BufferStream.Writable.end (C:\Users\xxxx\AppData\Roaming\npm\node_modules\ttf2woff2\node_modules\readable-st
ream\lib\_stream_writable.js:571:41)
    at Socket.onend (_stream_readable.js:513:10)
    at Object.onceWrapper (events.js:293:19)
```

**Comment by kolyaraketa** [comment]
same error

**Comment by MSSPL-KamalenduGarai** [comment]
any update on this. same error here!!
