### ISSUE TITLE
npm install  - ttf2woff2 - node-gyp rebuild error: no matching member function for call to 'ToObject'

### ISSUE THREAD

**Issue by mystikodesign** [nfroidure/ttf2woff2#49]
System Darwin 18.5.0
node -v v12.1.0
node-gyp -v v3.8.0
npm 6.9.0

'npm install' errors when it reaches ttf2woff2@2.0.3 install:

> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:10:40: error: no matching member function for call to 'ToObject'
  Local<Object> inputBuffer = info[0]->ToObject();
                              ~~~~~~~~~^~~~~~~~
/Users/stnaj/.node-gyp/12.1.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/stnaj/.node-gyp/12.1.0/include/node/v8.h:2546:35: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                    Local<Object> ToObject(Isolate* isolate) const);
                                  ^
1 error generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/Cellar/node/12.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/stnaj/Documents/Work/a2-clients/sites/604_cbaReferral/node_modules/ttf2woff2
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

**Comment by pioug** [comment]
Normally fixed in https://github.com/nfroidure/ttf2woff2/pull/51.

**Comment by pioug** [comment]
Fixed in https://github.com/nfroidure/ttf2woff2/releases/tag/v3.0.0
