### ISSUE TITLE
Build errors under node v0.10.x

### ISSUE THREAD

**Issue by MrFusion42** [nfroidure/ttf2woff2#8]
When installing the module under node v0.10.x (tried 0.10.30, 0.10.38 and 0.10.40), node-gyp throws lots of build errors.

```
> ttf2woff2@1.2.2 install /Users/mrfusion/repos/iris/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
> (node-gyp rebuild > builderror.log) || (exit 0)

../csrc/addon.cc:9:20: error: unknown type name 'FunctionCallbackInfo'
void Convert(const FunctionCallbackInfo<Value>& args) {
                   ^
../csrc/addon.cc:9:40: error: expected ')'
void Convert(const FunctionCallbackInfo<Value>& args) {
                                       ^
../csrc/addon.cc:9:13: note: to match this '('
void Convert(const FunctionCallbackInfo<Value>& args) {
            ^
../csrc/addon.cc:11:15: error: no matching constructor for initialization of 'v8::HandleScope'
  HandleScope scope(isolate);
              ^     ~~~~~~~
/Users/mrfusion/.node-gyp/0.10.40/deps/v8/include/v8.h:473:3: note: candidate constructor not viable: no known conversion from 'v8::Isolate *' to 'const v8::HandleScope' for 1st argument
  HandleScope(const HandleScope&);
  ^
/Users/mrfusion/.node-gyp/0.10.40/deps/v8/include/v8.h:448:3: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
  HandleScope();
  ^
../csrc/addon.cc:13:7: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (args.Length() < 1) {
      ^~~~
      uv_process_options_s::args
/Users/mrfusion/.node-gyp/0.10.40/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:13:7: error: invalid use of non-static data member 'args'
  if (args.Length() < 1) {
      ^~~~
../csrc/addon.cc:14:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:15:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Wrong number of arguments")));
        ~~~~~~~~^
../csrc/addon.cc:19:8: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  if (!args[0]->IsObject()) {
       ^~~~
       uv_process_options_s::args
/Users/mrfusion/.node-gyp/0.10.40/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:19:8: error: invalid use of non-static data member 'args'
  if (!args[0]->IsObject()) {
       ^~~~
../csrc/addon.cc:20:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:21:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Not an object")));
        ~~~~~~~~^
../csrc/addon.cc:25:31: error: use of undeclared identifier 'args'; did you mean 'uv_process_options_s::args'?
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
                              uv_process_options_s::args
/Users/mrfusion/.node-gyp/0.10.40/deps/uv/include/uv.h:1345:10: note: 'uv_process_options_s::args' declared here
  char** args;
         ^
../csrc/addon.cc:25:31: error: invalid use of non-static data member 'args'
  Local<Object> inputBuffer = args[0]->ToObject();
                              ^~~~
../csrc/addon.cc:28:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:29:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "First arg should be a Buffer")));
        ~~~~~~~~^
../csrc/addon.cc:45:14: error: no member named 'ThrowException' in 'v8::Isolate'
    isolate->ThrowException(Exception::TypeError(
    ~~~~~~~  ^
../csrc/addon.cc:46:17: error: no member named 'NewFromUtf8' in 'v8::String'
        String::NewFromUtf8(isolate, "Could not convert the given font.")));
        ~~~~~~~~^
../csrc/addon.cc:49:30: error: no matching function for call to 'New'
  Local<Object> slowBuffer = node::Buffer::New(isolate, output_length);
                             ^~~~~~~~~~~~~~~~~
/Users/mrfusion/.node-gyp/0.10.40/src/node_buffer.h:123:18: note: candidate function not viable: no known conversion from 'v8::Isolate *' to 'const char *' for 1st argument
  static Buffer* New(const char *data, size_t len);
                 ^
/Users/mrfusion/.node-gyp/0.10.40/src/node_buffer.h:116:33: note: candidate function not viable: requires single argument 'string', but 2 arguments were provided
  static v8::Handle<v8::Object> New(v8::Handle<v8::String> string);
                                ^
/Users/mrfusion/.node-gyp/0.10.40/src/node_buffer.h:121:18: note: candidate function not viable: requires single argument 'length', but 2 arguments were provided
  static Buffer* New(size_t length);
                 ^
/Users/mrfusion/.node-gyp/0.10.40/src/node_buffer.h:129:32: note: candidate function not viable: requires single argument 'args', but 2 arguments were provided
  static v8::Handle<v8::Value> New(const v8::Arguments &args);
                               ^
/Users/mrfusion/.node-gyp/0.10.40/src/node_buffer.h:125:18: note: candidate function not viable: requires 4 arguments, but 2 were provided
  static Buffer* New(char *data, size_t length,
                 ^
../csrc/addon.cc:52:38: error: no member named 'GetCurrentContext' in 'v8::Isolate'
  Local<Object> globalObj = isolate->GetCurrentContext()->Global();
                            ~~~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/addon/csrc/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mrfusion/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/mrfusion/.nvm/v0.10.40/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/mrfusion/repos/iris/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
ttf2woff2@1.2.2 /Users/mrfusion/repos/iris/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2
```

This, however, does not happen with node v0.12.x

**Comment by MrFusion42** [comment]
Looks like [Nan](https://github.com/nodejs/nan) helps in providing compatibility across different versions of node.js and io.js, but using it may require a rather large refactor in C/C++ code :(

**Comment by nfroidure** [comment]
@MrFusion42 there has been large changes between the C/C++  wrapper from 0.10 to 0.12 and i decided to only support the 0.12 engine. Feel free to PR the project with a correct 'engines' spec in the package.json.

You can also create a 0.10 version if you wish, just create a new branch and i'll submit it to NPM separately.

**Comment by MrFusion42** [comment]
Thanks for the fast response.  I've submitted a PR #9 to add `engines` to the `package.json` file.

**Comment by nfroidure** [comment]
Great, let's close. Anyone wanting to support 0.10 can submit a PR an reopen this issue.

**Comment by nfroidure** [comment]
@MrFusion42 since the module uses nan, it could work in node 0.10, if you succesfully use it in this version, then feel free to PR to add this engine.

**Comment by MrFusion42** [comment]
Thanks, but I've switched to 0.12 since
